version: '3'

services:
  main-website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: resume-generator-main

  # The resume-viewer-builder service is now commented out
  # It will be built and used by the main service only when needed
  #resume-viewer-builder:
  #  build:
  #    context: .
  #    dockerfile: resume-template/Dockerfile.build
  #  image: resume-viewer
  #  container_name: resume-viewer-builder