version: '3'

services:
  main-website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: resume-generator-main

  # Uncomment to build the fixed professional template image
  professional-resume-builder:
    build:
      context: .
      dockerfile: professional-template/Dockerfile.build
    image: professional-resume-viewer
    container_name: professional-resume-builder